### ISSUE TITLE
How do you build this kernel? 

### ISSUE THREAD

**Issue by redex557** [ktommy91/kernel_xiaomi_sdm710#1]
Hello,
really like your kernels I used before and want to run this on my Mi 9 Lite (pyxis). Whats the state of this project, how do you build this kernel and do you want to post a thread on XDA when you are ready?

**Comment by ktommy91** [comment]
The kernel is working with android 10 but has FOD issue with the recent MIUI beta builds. I hope this will be solved in the q source. I use GCC 9.2 toolchain to build. Ill post on XDA a bit later. Builds already available here: https://bit.ly/2QPkGNh
